import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,createHash} from 'node:crypto';import {createServer} from 'node:http';
import {createOAuth,providerConfiguration} from '../lib/oauth.mjs';import {createRequestListener} from '../server.mjs';import {memoryStore} from '../lib/store.mjs';import {createOwnerVerifier} from '../lib/google-owner.mjs';import {createOidcAdapter} from '../lib/oidc-storage.mjs';
function backend(){let state=new Map();return {read:async k=>structuredClone(state.get(k)??null),update:async(k,fn)=>{const {value,result}=fn(structuredClone(state.get(k)??null));if(value!==undefined)state.set(k,structuredClone(value));return result;}};}
const config={origin:'https://probe.example',resource:'https://probe.example/mcp',googleClientId:'123-fixture.apps.googleusercontent.com',ownerEmail:'fixture@gmail.com',redirects:['https://chatgpt.com/connector_platform_oauth_redirect'],cookieKeys:['SYNTHETIC-LOCAL-TEST-COOKIE-KEY-DO-NOT-DEPLOY'],jwks:{keys:[{...generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({format:'jwk'}),use:'sig',alg:'RS256',kid:'ephemeral-test-only'}]}};
test('プロバイダ設定はPKCE・厳密なresource・リダイレクト許可リストを必須にする',async()=>{const c=providerConfiguration(config,backend());assert.equal(c.pkce.required(),true);assert.equal(c.features.clientIdMetadataDocument.enabled,false);await assert.rejects(c.features.resourceIndicators.getResourceServerInfo({},'https://attacker.example'));assert.throws(()=>c.extraClientMetadata.validator(null,null,null,{token_endpoint_auth_method:'none',redirect_uris:['https://attacker.example']}));});
test('Googleログインは誤ったnonce/emailを拒否しsubjectを固定する',async()=>{const b=backend();let payload={iss:'https://accounts.google.com',aud:config.googleClientId,nonce:'nonce',email:'fixture@gmail.com',email_verified:true,sub:'test-sub'};const verify=createOwnerVerifier({google:{verifyIdToken:async()=>({getPayload:()=>payload})},config,backend:b});assert.equal(await verify('mock-token','nonce'),'google:test-sub');await assert.rejects(verify('mock-token','wrong'));payload={...payload,sub:'other-sub'};await assert.rejects(verify('mock-token','nonce'));payload={...payload,email:'other@gmail.com'};await assert.rejects(verify('mock-token','nonce'));});
test('OAuthの消費と失効はアダプタ再構築を越えて残る',async()=>{const b=backend();const A=createOidcAdapter(b);const a=new A('AuthorizationCode');await a.upsert('dummy',{grantId:'grant'},100);await a.consume('dummy');await assert.rejects(a.consume('dummy'));await a.revokeByGrantId('grant');assert.equal(await new (createOidcAdapter(b))('AuthorizationCode').find('dummy'),undefined);await assert.rejects(a.upsert('dummy2',{grantId:'grant'},100));});
test('ローカルOAuth DCR、Googleモックログイン、同意、PKCE交換、resource束縛RPC',async t=>{
 const b=backend();let nonce='';const auth=createOAuth({config,backend:b,google:{verifyIdToken:async()=>({getPayload:()=>({iss:'https://accounts.google.com',aud:config.googleClientId,nonce,email:'fixture@gmail.com',email_verified:true,sub:'test-sub'})})}});
 const server=createServer(createRequestListener({auth,store:memoryStore(),transport:()=>{throw Error('External callbacks disabled');}}));
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const base='http://127.0.0.1:'+server.address().port;const cookies=new Map();
 async function call(path,{method='GET',body,headers={}}={}){const url=new URL(path,config.origin);assert.equal(url.origin,config.origin);const r=await fetch(base+url.pathname+url.search,{method,body,headers:{host:'probe.example','x-forwarded-proto':'https',cookie:[...cookies].map(([k,v])=>k+'='+v).join('; '),...headers},redirect:'manual'});for(const cookie of r.headers.getSetCookie()){const [pair]=cookie.split(';');const ix=pair.indexOf('=');cookies.set(pair.slice(0,ix),pair.slice(ix+1));}return r;}
 const discovery=await (await call('/.well-known/oauth-authorization-server',{headers:{'x-forwarded-host':'attacker.example',forwarded:'host=attacker.example;proto=http'}})).json();assert.equal(discovery.authorization_endpoint,config.origin+'/auth');assert.equal(discovery.dpop_signing_alg_values_supported,undefined);assert.equal(discovery.authorization_response_iss_parameter_supported,true);assert.deepEqual(discovery.code_challenge_methods_supported,['S256']);
 const bad=await call('/reg',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({redirect_uris:['https://attacker.example'],token_endpoint_auth_method:'none'})});assert.equal(bad.status,400);
 const registration=await call('/reg',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({redirect_uris:config.redirects,token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code']})});const client=await registration.json();assert.equal(registration.status,201,JSON.stringify(client));assert.equal(client.client_secret,undefined);assert.equal(client.registration_access_token,undefined);
 const verifier='SYNTHETIC-TEST-ONLY-PKCE-VERIFIER-012345678901234567890';const challenge=createHash('sha256').update(verifier).digest('base64url');
 const q=new URLSearchParams({client_id:client.client_id,redirect_uri:config.redirects[0],response_type:'code',scope:'openid offline_access probe',resource:config.resource,code_challenge:challenge,code_challenge_method:'S256',state:'test-state',prompt:'consent'});
 const first=await call('/auth?'+q);assert.equal(first.status,303);const loginPath=first.headers.get('location');nonce=new URL(loginPath).pathname.split('/').at(-1);
 assert.equal((await call(loginPath)).status,200);
 const login=await call(loginPath,{method:'POST',headers:{'content-type':'application/json',origin:config.origin},body:JSON.stringify({action:'login',credential:'mock-google-id-token'})});const loginValue=await login.json();assert.equal(login.status,200,JSON.stringify(loginValue));
 const resume=await call(loginValue.redirect);assert.equal(resume.status,303);const consentPath=resume.headers.get('location');assert.equal((await call(consentPath)).status,200);
 const consent=await call(consentPath,{method:'POST',headers:{'content-type':'application/json',origin:config.origin},body:JSON.stringify({action:'consent'})});const consentValue=await consent.json();assert.equal(consent.status,200,JSON.stringify(consentValue));
 const authorized=await call(consentValue.redirect);assert.equal(authorized.status,303);const redirect=new URL(authorized.headers.get('location'));assert.equal(redirect.origin,'https://chatgpt.com');assert.equal(redirect.searchParams.get('iss'),config.origin);assert.ok(redirect.searchParams.get('code'));
 const tokenResponse=await call('/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:client.client_id,code:redirect.searchParams.get('code'),redirect_uri:config.redirects[0],code_verifier:verifier,resource:config.resource})});const token=await tokenResponse.json();assert.equal(tokenResponse.status,200,JSON.stringify(token));assert.ok(token.access_token);assert.ok(token.refresh_token);
 const rpc=await call('/mcp',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token.access_token},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'probe_status'}})});assert.equal(rpc.status,200);assert.ok((await rpc.json()).result);
 const beforeReplay=await b.read('oauth-state:v1');
 const replay=await call('/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:client.client_id,code:redirect.searchParams.get('code'),redirect_uri:config.redirects[0],code_verifier:verifier,resource:config.resource})});assert.equal(replay.status,400);
 await b.update('oauth-state:v1',()=>({value:beforeReplay})); // 独立した有効期限ブランチ。この隔離テストバックエンド専用。
 await b.update('oauth-state:v1',state=>{for(const [key,row] of Object.entries(state.records))if(JSON.parse(key)[0]==='Grant')row.expires=1;return {value:state};});
 const expiredGrant=await call('/mcp',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token.access_token},body:JSON.stringify({jsonrpc:'2.0',id:2,method:'ping'})});assert.equal(expiredGrant.status,401);
 const denied=await call('/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':'forged'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'ping'})});assert.equal(denied.status,401);
});

test('DCRクライアントは人工的な期限なく永続化される',async()=>{const b=backend();let now=100;const A=createOidcAdapter(b,{now:()=>now});const clients=new A('Client');await clients.upsert('public-client',{client_id:'public-client'});now+=172800;assert.equal((await clients.find('public-client')).client_id,'public-client');});

test('匿名モデルの上限は承認済みトークン用にストレージ容量を確保する',async()=>{const b=backend();const A=createOidcAdapter(b);const clients=new A('Client');for(let i=0;i<16;i++)await clients.upsert('client'+i,{client_id:'client'+i});await assert.rejects(clients.upsert('overflow',{client_id:'overflow'}));await new A('AccessToken').upsert('mock-token',{accountId:'mock-owner'},100);assert.ok(await new A('AccessToken').find('mock-token'));});
